/**
 * CODEOWNERS Generator
 *
 * Generates a GitHub CODEOWNERS file from the zone ownership map.
 * This enforces that PRs changing files in a zone must be reviewed
 * by the zone owner.
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate the CODEOWNERS file
 *
 * @param {string} projectRoot
 * @param {object} config - The .ofa/config.yml content
 */
export function generateCodeowners(projectRoot, config) {
  // Prefer .github/CODEOWNERS location
  const outputDir = path.join(projectRoot, '.github');
  const outputFile = path.join(outputDir, 'CODEOWNERS');

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const content = buildCodeownersContent(config);
  fs.writeFileSync(outputFile, content, 'utf-8');
  return outputFile;
}

function buildCodeownersContent(config) {
  const lines = [];

  lines.push('# CODEOWNERS — Generated by ONEFORALL (ofa)');
  lines.push('#');
  lines.push('# This file defines code ownership for PR review enforcement.');
  lines.push('# Edit .ofa/config.yml and run `ofa sync` to regenerate.');
  lines.push('#');
  lines.push('# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners');
  lines.push('');

  let hasOwners = false;

  for (const [name, zone] of Object.entries(config.zones)) {
    if (!zone.owner) continue;
    hasOwners = true;

    lines.push(`# Zone: ${name} — ${zone.description}`);
    for (const zonePath of zone.paths) {
      // Convert zone paths to CODEOWNERS glob patterns
      const codeownersPath = zonePath.startsWith('/') ? zonePath : '/' + zonePath;
      lines.push(`${codeownersPath}    @${zone.owner}`);
    }
    lines.push('');
  }

  if (!hasOwners) {
    lines.push('# No zones are currently claimed. Run `ofa claim <zone> --user <username>` to assign ownership.');
    lines.push('# Once zones are claimed, re-run `ofa sync` to populate this file.');
    lines.push('');
  }

  // Shared zones — require all owners
  const sharedZones = Object.entries(config.zones).filter(([_, z]) => z.require_all_owners);
  const allOwners = Object.values(config.zones)
    .filter(z => z.owner && !z.require_all_owners)
    .map(z => `@${z.owner}`);

  if (sharedZones.length > 0 && allOwners.length > 0) {
    lines.push('# Shared zones — require review from all active owners');
    for (const [name, zone] of sharedZones) {
      lines.push(`# Zone: ${name} (shared)`);
      for (const zonePath of zone.paths) {
        const codeownersPath = zonePath.startsWith('/') ? zonePath : '/' + zonePath;
        lines.push(`${codeownersPath}    ${allOwners.join(' ')}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}
