/**
 * GitHub Copilot Instructions Generator
 *
 * Generates .github/copilot-instructions.md that tells Copilot
 * about the developer's ownership zone and boundaries.
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate the copilot-instructions.md file
 *
 * @param {string} projectRoot
 * @param {object} config - The .ofa/config.yml content
 */
export function generateCopilotInstructions(projectRoot, config) {
  const outputDir = path.join(projectRoot, '.github');
  const outputFile = path.join(outputDir, 'copilot-instructions.md');

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const content = buildCopilotContent(config);
  fs.writeFileSync(outputFile, content, 'utf-8');
  return outputFile;
}

function buildCopilotContent(config) {
  const lines = [];

  lines.push('# Copilot Instructions — Generated by ONEFORALL (ofa)');
  lines.push('');
  lines.push('> ⚠️ This file is auto-generated. Edit `.ofa/config.yml` and run `ofa sync` to update.');
  lines.push('');

  // Project info
  lines.push(`## Project: ${config.project.name}`);
  lines.push(`- **Type:** ${config.project.type}`);
  lines.push('');

  // Ownership zones
  lines.push('## Ownership Zones');
  lines.push('');
  lines.push('This project uses ONEFORALL zone-based ownership. Multiple developers and their');
  lines.push('AI agents collaborate by respecting these boundaries:');
  lines.push('');

  for (const [name, zone] of Object.entries(config.zones)) {
    const owner = zone.owner ? `@${zone.owner}` : '_unclaimed_';
    const sharedTag = zone.require_all_owners ? ' 🔒 (shared — requires all owners approval)' : '';
    lines.push(`### Zone: \`${name}\`${sharedTag}`);
    lines.push(`- **Owner:** ${owner}`);
    lines.push(`- **Paths:** ${zone.paths.map(p => `\`${p}\``).join(', ')}`);
    lines.push(`- **Description:** ${zone.description}`);
    lines.push('');
  }

  // Rules
  lines.push('## Rules for AI Agents');
  lines.push('');
  for (const rule of config.rules || []) {
    lines.push(`- ${rule}`);
  }
  lines.push('');

  // Critical instructions
  lines.push('## Critical Boundaries');
  lines.push('');
  lines.push('**IMPORTANT:** Before modifying ANY file, check if it falls within your assigned zone.');
  lines.push('If you are editing files outside your zone, STOP and inform the developer.');
  lines.push('');

  const claimedZones = Object.entries(config.zones).filter(([_, z]) => z.owner);
  if (claimedZones.length > 0) {
    lines.push('### Active Ownership Map');
    lines.push('');
    lines.push('| Zone | Owner | Paths |');
    lines.push('|------|-------|-------|');
    for (const [name, zone] of claimedZones) {
      lines.push(`| ${name} | @${zone.owner} | ${zone.paths.join(', ')} |`);
    }
    lines.push('');
    lines.push('**DO NOT modify files in zones owned by other developers.**');
  }

  lines.push('');
  lines.push('---');
  lines.push('_Generated by [ONEFORALL](https://github.com/oneforall-ai/oneforall) — Universal AI Collaboration Tool_');

  return lines.join('\n');
}
