/**
 * Cursor Rules Generator
 *
 * Generates .cursor/rules/ofa-ownership.mdc that tells Cursor
 * about the developer's ownership zone and boundaries.
 * Uses the modern .mdc format with YAML frontmatter.
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate the Cursor rules file
 *
 * @param {string} projectRoot
 * @param {object} config - The .ofa/config.yml content
 */
export function generateCursorRules(projectRoot, config) {
  const outputDir = path.join(projectRoot, '.cursor', 'rules');
  const outputFile = path.join(outputDir, 'ofa-ownership.mdc');

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const content = buildCursorContent(config);
  fs.writeFileSync(outputFile, content, 'utf-8');
  return outputFile;
}

function buildCursorContent(config) {
  // Build glob patterns for all zone paths
  const allPaths = [];
  for (const zone of Object.values(config.zones)) {
    for (const p of zone.paths) {
      allPaths.push(`${p}**/*`);
    }
  }

  const lines = [];

  // YAML frontmatter for Cursor
  lines.push('---');
  lines.push('description: "ONEFORALL ownership boundaries — DO NOT edit manually, run ofa sync"');
  lines.push(`globs: ${JSON.stringify(allPaths)}`);
  lines.push('alwaysApply: true');
  lines.push('---');
  lines.push('');

  // Instructions
  lines.push('# ONEFORALL — Zone Ownership Rules');
  lines.push('');
  lines.push('This project uses ONEFORALL (ofa) for multi-developer AI collaboration.');
  lines.push('**You MUST respect zone ownership boundaries.**');
  lines.push('');

  // Current ownership map
  lines.push('## Current Ownership');
  lines.push('');

  for (const [name, zone] of Object.entries(config.zones)) {
    const owner = zone.owner ? `@${zone.owner}` : 'UNCLAIMED';
    const paths = zone.paths.map(p => `\`${p}\``).join(', ');
    const shared = zone.require_all_owners ? ' ⚠️ SHARED ZONE' : '';
    lines.push(`- **${name}** (${owner}${shared}): ${paths}`);
    lines.push(`  - ${zone.description}`);
  }
  lines.push('');

  // Rules
  lines.push('## Enforcement Rules');
  lines.push('');
  lines.push('1. **BEFORE editing any file**, determine which zone it belongs to.');
  lines.push('2. **If the zone has an owner that is NOT you**, do NOT edit the file. Instead:');
  lines.push('   - Inform the developer that the change requires coordination.');
  lines.push('   - Suggest creating an issue or PR for the zone owner to handle.');
  lines.push('3. **If the zone is a shared zone**, any changes require review from ALL active zone owners.');
  lines.push('4. **Always work on a feature branch**, never commit directly to main.');
  lines.push('5. **Keep changes minimal and focused** — touch only files within your assigned zone.');
  lines.push('');

  // Project rules
  if (config.rules && config.rules.length > 0) {
    lines.push('## Project Rules');
    lines.push('');
    for (const rule of config.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Auto-generated by ONEFORALL (ofa) — do not edit manually_');

  return lines.join('\n');
}
