/**
 * Gemini / Antigravity Instructions Generator
 *
 * Generates GEMINI.md at the project root with zone ownership
 * context for Google Gemini CLI, Antigravity IDE, and any other
 * tool that reads GEMINI.md or AGENTS.md.
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate GEMINI.md and AGENTS.md files
 *
 * @param {string} projectRoot
 * @param {object} config - The .ofa/config.yml content
 */
export function generateGeminiInstructions(projectRoot, config) {
  const content = buildGeminiContent(config);

  // Write GEMINI.md
  const geminiFile = path.join(projectRoot, 'GEMINI.md');
  fs.writeFileSync(geminiFile, content, 'utf-8');

  // Also write AGENTS.md (used by GitHub Copilot agents and others)
  const agentsFile = path.join(projectRoot, 'AGENTS.md');
  fs.writeFileSync(agentsFile, content, 'utf-8');

  return [geminiFile, agentsFile];
}

function buildGeminiContent(config) {
  const lines = [];

  lines.push('# ONEFORALL — AI Collaboration Guidelines');
  lines.push('');
  lines.push('> ⚠️ Auto-generated by ONEFORALL (ofa). Edit `.ofa/config.yml` and run `ofa sync` to update.');
  lines.push('');

  lines.push(`## Project: ${config.project.name} (${config.project.type})`);
  lines.push('');
  lines.push('This project uses **ONEFORALL** for multi-developer AI collaboration.');
  lines.push('Multiple developers use different AI coding tools (Cursor, Copilot, Gemini, Claude)');
  lines.push('and their agents must coordinate to avoid merge conflicts.');
  lines.push('');

  // Zone map
  lines.push('## Zone Ownership Map');
  lines.push('');
  lines.push('Each directory/area of the codebase is assigned to a **zone**. Each zone can be');
  lines.push('**claimed** by one developer at a time. You must only modify files within zones');
  lines.push('that your developer has claimed.');
  lines.push('');

  for (const [name, zone] of Object.entries(config.zones)) {
    const status = zone.owner
      ? `🔴 Claimed by **@${zone.owner}**`
      : '🟢 Available';
    const shared = zone.require_all_owners
      ? ' *(shared zone — changes need all-owner review)*'
      : '';

    lines.push(`### ${name} — ${status}${shared}`);
    lines.push(`- Paths: ${zone.paths.map(p => `\`${p}\``).join(', ')}`);
    lines.push(`- ${zone.description}`);
    lines.push('');
  }

  // Strict rules
  lines.push('## Strict Rules');
  lines.push('');
  lines.push('1. **CHECK OWNERSHIP FIRST.** Before editing ANY file, identify which zone it belongs to.');
  lines.push('2. **DO NOT edit files in zones owned by another developer.** If you need a change in their');
  lines.push('   zone, communicate with them — do not make the change yourself.');
  lines.push('3. **Shared zones require ALL active owners to review** before merging.');
  lines.push('4. **Always use feature branches.** Never commit directly to `main` or `master`.');
  lines.push('5. **Run `ofa guard` before committing** to verify you haven\'t crossed boundaries.');
  lines.push('');

  // Custom rules
  if (config.rules && config.rules.length > 0) {
    lines.push('## Additional Project Rules');
    lines.push('');
    for (const rule of config.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');
  }

  // How to use
  lines.push('## Quick Reference');
  lines.push('');
  lines.push('```bash');
  lines.push('ofa status          # See who owns what');
  lines.push('ofa claim <zone>    # Claim a zone for yourself');
  lines.push('ofa release <zone>  # Release a zone');
  lines.push('ofa guard           # Check your changes respect boundaries');
  lines.push('ofa sync            # Regenerate all AI config files');
  lines.push('```');
  lines.push('');

  lines.push('---');
  lines.push('_Generated by [ONEFORALL](https://github.com/oneforall-ai/oneforall) — Universal AI Collaboration Tool_');

  return lines.join('\n');
}
